version: '2'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - api
    volumes:
      - pg:/var/lib/postgresql/data
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env.docker
    ports:
      - "3000:3000"
    networks:
      - api
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - api
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env.docker
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  pg:
