name: Lint (Backend)

on:
  pull_request:
    paths:
      - 'backend/**'
      - 'tasks/**'

jobs:
  run-linter-tasks:
    name: Run Lint (Tasks)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run black linter
        uses: psf/black@stable
        with:
          options: '--check --versbose'
          src: "./tasks"

  run-linter-backend:
    name: Run Lint (Backend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install packages
        working-directory: ./backend
        run: npm ci

      - name: Run linter
        working-directory: ./backend
        run: npm run lint
